name: Helm Deploy

on:
  push:
    branches-ignore:
      - '*'
#   push:
#     branches: [ master ]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: filario
  CLUSTER_NAME: cluster-name
  CLUSTER_RESOURCE_GROUP: cluster-resource-group
  NAMESPACE: namespace
  CHART_PATH: ./build/helm/go-std-tmpl/
  PROJECT_NAME: go-std-tmpl

jobs:
  
  build: 
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@master

      # Connect to Azure Container registry (ACR)
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: benjlevesque/short-sha@v1.1
        id: short-sha
        with:
          length: 7
      - run: echo $SHA
        env: 
          SHA: ${{ steps.short-sha.outputs.sha }}

      # Container build and push to a Azure Container registry (ACR)
      - run: |
          docker build -t ${{ env.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}:${{ env.SHA }} -f build/docker/app/Dockerfile .
          docker push ${{ env.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}:${{ env.SHA }}

      # Set the target Azure Kubernetes Service (AKS) cluster.
      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      # Create namespace if doesn't exist
      - run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
      
      - run: |
          CHART_VERSION=$(helm show chart ${{ env.CHART_PATH }} | grep "version: " | sed -E 's/^version: (.*?)$/\1/')
          CHART_NAME=$(helm show chart ${{ env.CHART_PATH }} | grep "name: " | sed -E 's/^name: (.*?)$/\1/')
          
          helm lint ${{ env.CHART_PATH }}
          helm package ${{ env.CHART_PATH }}
          helm upgrade --install --namespace ${{ env.NAMESPACE }} ${{ env.PROJECT_NAME }} $CHART_NAME-$CHART_VERSION.tgz --set image.tag=${{ env.SHA }}
